### ISSUE TITLE
Create a new branch named DevSamba

### ISSUE THREAD

**Issue by companyabab** [companyabab/ShellScript#1]
Hey Samba,

Create a new branch named DevSamba .

Regards,
Company.

**Comment by vunnava123** [comment]
hai company,
i created new branch devsamba 
so that the issue is resolved

**Comment by companyabab** [comment]
Hey Samba ,

I requested to create DevSamba instead  of that you created devsamba. Plz, go through  it.

Thanks,
Company

**Comment by vunnava123** [comment]
hai company,
i gone through it and renamed the branch
thank you

**Comment by companyabab** [comment]
Good Job !!!

Verified.
